### ISSUE TITLE
Easier way to create a new "RequestBuilder" struct?

### ISSUE THREAD

**Issue by godbrigero** [ededddy/groq-api-rs#11]
Creating "RequestBuilder" struct gets quite lengthy if you have a custom configuration that you would like to load. [Example](https://paste.ofcode.org/S7DvYfuxYh5W8EAGZ8x3YC)

It would be much more useful to have either a class passed into the "new" function or have a function taking all of the parameters and loading them into the class.

**Comment by ededddy** [comment]
Make sense to me. I will add it today.

Update: 
Seems there is little way to make it beautiful. I will just add two methods.
1. Allow passing tons of options in and return the builder.
2. Copying another request builder (hash output should be the same)

**Comment by ededddy** [comment]
see PR #12
