### ISSUE TITLE
Groq param in structure useless

### ISSUE THREAD

**Issue by godbrigero** [ededddy/groq-api-rs#14]
Having "groq_instance" as a struct field is pretty useless since you cannot add messages to it at all ->

```
async fn send_request(
        &mut self,
        req: &crate::ai::request::Request,
    ) -> Option<crate::ai::response::Response> {
        let request: builder::RequestBuilder = self.get_builder_instance_based_on_config();

        self.groq_instance = **self.groq_instance**(error here).add_message(Message::UserMessage {
            content: Some(req.get_request_string().clone()),
            name: Some("user".to_string()),
            role: None,
            tool_call_id: None,
        });
}
```  

error: 

```
cannot move out of `__self.groq_instance` which is behind a mutable reference
move occurs because `__self.groq_instance` has type `Groq`, which does not implement the `Copy` trait
```

Maybe it is also best to make the "add_message" and other function take &mut self instead of just mut self (returning nothing also).

I think a quick fix would be to just add Clone atr to Groq struct but that would patch the hole but not the problem since Clone is slow to use for every req.

---- 

Very critical because there is literally no workaround other than creating a new instance of the struct.

**Comment by ededddy** [comment]
Ah I see. The current messages related methods are consuming the instance. Probably not ideal. Let's change/add different methods.

**Comment by ededddy** [comment]
@lolhol I drafted a PR which makes the vector operations non consuming. See #15

**Comment by godbrigero** [comment]
Great!
