### ISSUE TITLE
Readme not accurate

### ISSUE THREAD

**Issue by godbrigero** [ededddy/groq-api-rs#16]
The readme sample code is not up to date. As mentioned in #13 the new request format should contain 

let **mut** client = Groq::new()... 
... .request(client)...

and not 

let client = Groq::new()...
... .request(client)...

See #13 for more details about this change and it's reasoning.

**Comment by ededddy** [comment]
@lolhol I will fix it in pr #15.

**Comment by ededddy** [comment]
merged
