### ISSUE TITLE
Make "Groq" struct hashable?

### ISSUE THREAD

**Issue by godbrigero** [ededddy/groq-api-rs#9]
Hi!

I may not understand some of the consequences of making a struct Hashable via "#[derive(Hash)]", but could you do that? It would be very useful since, at the moment, I had to make a work-around by ->

`pub struct HashableGroq {
    groq_instance: Groq,
    identifier: String,
}

impl Hash for HashableGroq {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.identifier.hash(state);
    }
}

impl HashableGroq {
    pub fn new() -> Self {
        return Self {
            groq_instance: Groq::new(""),
            identifier: generate_random_string(10),
        };
    }

    pub fn get_groq_instance(&mut self) -> &mut Groq {
        return &mut self.groq_instance;
    }
}`

Thanks!

**Comment by ededddy** [comment]
I see. You are trying put `Groq` struct instances into a hash set.
That's totally understandable. I will try to add it without breaking the original code.

However, I am currently allocated to investigate micro-frontend for my boss.
You can submit a PR to add it. It's fine to me.

Let's keep in touch for this.

**Comment by godbrigero** [comment]
Hi!

Firstly, I wanted to thank you for the quick response. I will create the PR once I have some time.

Thanks!

**Comment by godbrigero** [comment]
Added PR.
